# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.CharField(max_length=10, unique=True, verbose_name='玩家ID')),
                ('playername', models.CharField(max_length=10, unique=True, verbose_name='玩家姓名')),
                ('level', models.PositiveIntegerField(verbose_name='玩家等级')),
                ('experience', models.PositiveIntegerField(verbose_name='玩家经验')),
                ('regtime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
        ),
        migrations.CreateModel(
            name='Player_gold_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverid', models.CharField(max_length=10, verbose_name='服务器ID')),
                ('gold_change', models.IntegerField(verbose_name='金币变化数量')),
                ('gold', models.PositiveIntegerField(verbose_name='金币剩余数量')),
                ('gold_change_time', models.DateTimeField(verbose_name='金币变化时间')),
                ('playerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_server.Player', verbose_name='玩家ID')),
            ],
        ),
    ]
