# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_user',
        ),
    ]
